### ISSUE TITLE
Problem with grid scan

### ISSUE THREAD

**Issue by wpertsch** [terrier-org/pyterrier#191]
**Describe the bug**
I can not perform the grid scan explained in the Docs (https://pyterrier.readthedocs.io/en/latest/tuning.html#parameter-scanning-and-searching-api) 

**To Reproduce**
```python
def runexperiment3():
   index = pt.IndexFactory.of("/Uni/retrievalsystem/evalpyterrier/wt2g_index/data.properties")
   pl2 = pt.BatchRetrieve(index, wmodel="PL2", controls={'c': 1})
   rtr = pt.GridSearch(
      pl2,
      {pl2: {'c': [0.1, 1, 5, 10, 20, 100]}},
      get_topics(),
      get_qrels(),
      [map]
   )
   import matplotlib.pyplot as plt
   print(rtr)
   plt.plot(rtr["tran_0_c"], rtr["map"])
   plt.xlabel("PL2's c value")
   plt.ylabel("MAP")
   plt.show()
```
This is the error:
```
PyTerrier 0.6.0 has loaded Terrier 5.5 (built by craigmacdonald on 2021-05-20 13:12)
No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
Traceback (most recent call last):
  File "/Uni/retrievalsystem/evalpyterrier/main.py", line 123, in <module>
    runexperiment3()
  File "/Uni/retrievalsystem/evalpyterrier/main.py", line 107, in runexperiment3
    [map]
  File "/Uni/retrievalsystem/evalpyterrier/backend/venv/lib/python3.7/site-packages/pyterrier/pipelines.py", line 579, in GridSearch
    dataframe=False)
  File "/Uni/retrievalsystem/evalpyterrier/backend/venv/lib/python3.7/site-packages/pyterrier/pipelines.py", line 709, in GridScan
    parameter_list, eval_scores = _evaluate_one_setting(keys, v)
  File "/Uni/retrievalsystem/evalpyterrier/backend/venv/lib/python3.7/site-packages/pyterrier/pipelines.py", line 699, in _evaluate_one_setting
    time, eval_scores = _run_and_evaluate(pipeline, topics, qrels, metrics, perquery=False, batch_size=batch_size)
  File "/Uni/retrievalsystem/evalpyterrier/backend/venv/lib/python3.7/site-packages/pyterrier/pipelines.py", line 115, in _run_and_evaluate
    metrics, rev_mapping = _convert_measures(metrics)
  File "/Uni/retrievalsystem/evalpyterrier/backend/venv/lib/python3.7/site-packages/pyterrier/pipelines.py", line 77, in _convert_measures
    assert len(rtr) > 0
AssertionError

Process finished with exit code 1
```
If I try the same code but with "map" instead of [map], the error ist this:

```
Traceback (most recent call last):
  File "/home/wilhelm/Uni/retrievalsystem/evalpyterrier/main.py", line 123, in <module>
    runexperiment3()
  File "/home/wilhelm/Uni/retrievalsystem/evalpyterrier/main.py", line 111, in runexperiment3
    plt.plot(rtr["tran_0_c"], rtr["map"])
  File "/home/wilhelm/Uni/retrievalsystem/evalpyterrier/backend/venv/lib/python3.7/site-packages/matchpy/expressions/expressions.py", line 207, in __getitem__
    raise IndexError("Invalid position")
IndexError: Invalid position
```

Any ideas how to fix this?

**Comment by cmacdonald** [comment]
Thanks for the report. `"map"` or `pyterrier.measures.MAP` should be the measure. I will investigate when I can and report back.

**Comment by cmacdonald** [comment]
I suspect `map` was an object of some other type. That should have been detected before the assertion. I will make a fix for that.

**Comment by wpertsch** [comment]
Ok thank you.
Is there another way to get back an array of the different Mean Average Precisions at different c's?
For me it would be nice to see some graphs.

**Comment by cmacdonald** [comment]
You can build a list comprehension in a `pt.Experiment()`:

```python
pt.Experiment(
 [pt.BatchRetrieve(index, wmodel="PL2", controls={'c': c}) for c in [0.1,,2,4,8]],
 topics,
 qrels,
 ["map"]
)
```

**Comment by cmacdonald** [comment]
Ok, this works:

```python
dataset = pt.get_dataset("vaswani")
index = dataset.get_index()
pl2 = pt.BatchRetrieve(index, wmodel="PL2", controls={'c': 1})
rtr = pt.GridScan(
  pl2,
  {pl2: {'c': [0.1, 1, 5, 10, 20, 100]}},
  dataset.get_topics(),
  dataset.get_qrels(),
  "map"
)
import matplotlib.pyplot as plt
print(rtr)
plt.plot(rtr["tran_0_c"], rtr["map"])
plt.xlabel("PL2's c value")
plt.ylabel("MAP")
plt.show()
```
as shown below:

![image](https://user-images.githubusercontent.com/620938/123097885-744e4900-d428-11eb-858f-329b2d677c94.png)

The error is in the [example of Grid**Scan**](https://pyterrier.readthedocs.io/en/latest/tuning.html#pyterrier.GridScan) which incorrectly shows Grid**Search**.

Furthermore, GridScan only supports a single measure. The fix committed earlier should address this.  I will shortly amend the documentation. Thanks for the feedback.

**Comment by cmacdonald** [comment]
Reported issues now fixed. Reopen if still having problems
