### ISSUE TITLE
Not able to index Trec-core-2017

### ISSUE THREAD

**Issue by bjoernengelmann** [terrier-org/pyterrier#266]
**Describe the bug**

The indexing of the trec-core-2017 dataset runs into an error.

```
import pyterrier as pt 
pt.init()
dataset = pt.get_dataset('irds:nyt/trec-core-2017')
indexer = pt.IterDictIndexer('./indices/nyt')
index_ref = indexer.index(dataset.get_corpus_iter(), fields=['headline', 'body'])
```

The indexing of trec-core-2018 works properly.

**To Reproduce**

5. See error
```
nyt/trec-core-2017 documents:   0%|                 | 0/1864661 [00:00<?, ?it/s]Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ub2010/PycharmProjects/repro_eval/venv/lib/python3.9/site-packages/pyterrier/index.py", line 758, in _write_fifos
    fifo = ready.popleft()
  File "/usr/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input within/between Object entries
 at [Source: (String)"{"headline": "MARSH & MCLENNAN INC reports earnings for Qtr to Dec 31", "body": "LEAD:\n*3*** COMPANY REPORTS **\n*3*MARSH & MCLENNAN INC (NYSE)\nQtr to Dec 31\n1986\n1985\nRevenue\n444,700,000\n361,700,000\nNet inc\n49,300,000\n36,700,000\nShare earns\n.67\n.50\nYr rev\n1,804,100,000\n1,367,600 000\nNet inc\n243,200,000\n162,900 000\nShare earns\n3.30\n2.23\n*3*** COMPANY REPORTS **\n*3*MARSH & MCLENNAN INC (NYSE)\nQtr to Dec 31\n1986\n1985\nRevenue\n444,700,000\n361,700,000\nNet inc\n49,300,00"[truncated 150 chars]; line: 1, column: 1301]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:618)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon2(ReaderBasedJsonParser.java:2222)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon(ReaderBasedJsonParser.java:2137)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:920)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:512)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3005)
	at org.terrier.indexing.FlatJSONDocument.initalize(FlatJSONDocument.java:75)
	at org.terrier.indexing.FlatJSONDocument.<init>(FlatJSONDocument.java:65)
	at org.terrier.python.JsonlDocumentIterator.next(JsonlDocumentIterator.java:41)
	at org.terrier.python.JsonlDocumentIterator.next(JsonlDocumentIterator.java:14)
	at org.terrier.python.CollectionFromDocumentIterator.nextDocument(CollectionFromDocumentIterator.java:27)
	at org.terrier.structures.indexing.classical.BasicIndexer.createDirectIndex(BasicIndexer.java:245)
	at org.terrier.structures.indexing.Indexer.index(Indexer.java:369)
	at org.terrier.python.ParallelIndexer$1.apply(ParallelIndexer.java:63)
	at org.terrier.python.ParallelIndexer$1.apply(ParallelIndexer.java:52)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at org.terrier.python.ParallelIndexer$3.call(ParallelIndexer.java:133)
	at org.terrier.python.ParallelIndexer$3.call(ParallelIndexer.java:130)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
/tmp/ipykernel_32151/4152241112.py in <module>
      1 indexer = pt.IterDictIndexer('./indices/nyt')
----> 2 index_ref = indexer.index(dataset.get_corpus_iter(), fields=['headline', 'body'])

~/PycharmProjects/repro_eval/venv/lib/python3.9/site-packages/pyterrier/index.py in index(self, it, fields, meta, meta_lengths)
    734                 return index.getIndex().getIndexRef()
    735 
--> 736             # Start the indexing threads
    737             ParallelIndexer.buildParallel(j_collections, self.index_dir, Indexer, Merger)
    738             return IndexRef.of(self.index_dir + "/data.properties")

jnius/jnius_export_class.pxi in jnius.JavaMethod.__call__()

jnius/jnius_export_class.pxi in jnius.JavaMethod.call_staticmethod()

jnius/jnius_jvm_dlopen.pxi in jnius.create_jnienv()

JavaException: JVM exception occurred: java.util.concurrent.ExecutionException: java.lang.NullPointerException java.lang.RuntimeException
```

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Additional context**
We have reproduced the error on another system. 
We have also tested different versions of PyTerrier.

**Comment by cmacdonald** [comment]
Thanks for the report. We'll give a look and get back to you. It might be informative for us if you could iterate through the corpus_iter to get to the document at hand:

```python

for d in pt.get_dataset('irds:nyt/trec-core-2017').get_corpus_iter():
  if d["headline"] == "MARSH & MCLENNAN INC reports earnings for Qtr to Dec 31":
    print d
    break

```

**Comment by seanmacavaney** [comment]
Hi @bjoernengelmann. Thanks for reporting. The problem arises because the `source_xml` field of the document is represented as binary data, rather than a string, and this cannot be encoded as JSON (which is the internal format used for sending data for indexing).

We can put a fix in place so that it doesn't encode fields that are not indexed or used as metadata, which will solve the issue long-term. But in the meantime, here's a workaround that removes the problematic field:

```python
def core_corpus_iter():
  for doc in dataset.get_corpus_iter():
    del doc['source_xml'] # delete the problematic field
    yield doc

index_ref = indexer.index(core_corpus_iter(), fields=['headline', 'body'])
```

**Comment by bjoernengelmann** [comment]
Thank you very much!

**Comment by cmacdonald** [comment]
Fix merged for next release. Thanks for the report @bjoernengelmann
