### ISSUE TITLE
com.github.luben.zstd.ZstdException: Unknown frame descriptor

### ISSUE THREAD

**Issue by coeywychan** [terrier-org/pyterrier#300]
I am following this notebook (https://colab.research.google.com/github/terrierteam/pyterrier_deepct/blob/main/pyterrier_deepct_vaswani.ipynb
) to train deepct model while I got the following error when I run the last cell: 

```
pt.Experiment([
  pt.BatchRetrieve(pt.get_dataset("vaswani").get_index(), wmodel="BM25"),
  pt.BatchRetrieve(indexref, wmodel="BM25"),
  ],
  dataset.get_topics(),
  dataset.get_qrels(),
  names=["BM25", "BM25_deepct"],
  eval_metrics=["map", "recip_rank"]
)
```

Error message:
```
10:18:42.931 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:42.970 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Src size is incorrect
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.004 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.038 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.077 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.117 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.154 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Src size is incorrect
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.189 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.222 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.257 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
10:18:43.293 [main] WARN org.terrier.querying.SimpleDecorate - Problem performing decoration
com.github.luben.zstd.ZstdException: Unknown frame descriptor
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:157)
	at com.github.luben.zstd.ZstdDecompressCtx.decompress(ZstdDecompressCtx.java:214)
	at org.terrier.structures.ZstdCompressedMetaIndex.decode(ZstdCompressedMetaIndex.java:45)
	at org.terrier.structures.BaseCompressingMetaIndex.getItems(BaseCompressingMetaIndex.java:889)
	at org.terrier.querying.SimpleDecorate.filter(SimpleDecorate.java:61)
	at org.terrier.querying.LocalManager$PostFilterProcess.process(LocalManager.java:811)
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:895)
```

What could be the cause of this issue?

**Comment by cmacdonald** [comment]
Nothing hear, assuming resolved
