### ISSUE TITLE
Indexing does not work for non-English(Persian)

### ISSUE THREAD

**Issue by poorya2021** [terrier-org/pyterrier#309]
Hello
I encounter this problem when I want to index Persian documents
Thank you for your help

code:
```
pd_indexer = pt.DFIndexer(addr_index, verbose=True)
pd_indexer.setProperty("tokeniser", "IdentityTokeniser")  
pd_indexer.setProperty("termpipelines", "")
indexref = pd_indexer.index(c_df['text'], c_df['docno'])
```

log:
```
ERROR org.terrier.structures.seralization.FixedSizeTextFactory - Term   ?????? ?? ??? ??? ???? ??????? ?????? ?? ???? ??? ?????? ?? ????? ?? ??? ????? ?? ?? ??? ?? ??? (??? ?? ???? ??? FidoNet ?????? ??? ??????). ???????? ????? ??? ??? ???? ?? ??? ?? ?? ????? ??????? ???? ??????? ???? ?? ??? ??? ??? ????? ??? ? ?? ??? ??? ????????? ??? ???? ??? ?????? ?? ??? ??????? ????? ???. ??? ????? ??? ?? ?????? ??? ????? ????? ??????? ?? ????? ??? ?????? ???? ?? ????? ?? ???? ???? ???? ??? ? ?????? ?? ????? ??? ? ?????????? ?????? ??? ??????? ?? ????? ??????? ??????? ? ?????? ???? ????????? ????? ? ??? ??????? ?? ???? ???? ????? ????? ??? ?? ?? ?? ??? ???? ?? ??? ?? ???. ????? ?????? ??????? ??????? ????? ???? ?? ?? ????? ????? ???? ??????? ??????.'' written in 1212 bytes. Max expected size was 61. Increase relevant property: max.term.length for Lexicon, or indexer.meta.forward.keylens for metadata
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1151 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:129)
	at java.base/java.io.DataOutputStream.write(DataOutputStream.java:112)
	at org.terrier.structures.seralization.FixedSizeTextFactory$FixedSizeText.write(FixedSizeTextFactory.java:75)
	at org.terrier.structures.collections.FSOrderedMapFile$1.write(FSOrderedMapFile.java:1163)
	at org.terrier.structures.FSOMapFileLexiconOutputStreamGeneric.writeNextEntry(FSOMapFileLexiconOutputStreamGeneric.java:100)
	at org.terrier.structures.indexing.LexiconMap.storeToStream(LexiconMap.java:118)
	at org.terrier.structures.indexing.LexiconBuilder.writeTemporaryLexicon(LexiconBuilder.java:341)
	at org.terrier.structures.indexing.LexiconBuilder.finishedDirectIndexBuild(LexiconBuilder.java:409)
	at org.terrier.structures.indexing.classical.BasicIndexer.createDirectIndex(BasicIndexer.java:352)
	at org.terrier.structures.indexing.Indexer.index(Indexer.java:369)
```

**Comment by cmacdonald** [comment]
Glad you got it fixed
