### ISSUE TITLE
Various errors when a previous pipeline component returns an empty dataframe

### ISSUE THREAD

**Issue by prithvidasgupta** [terrier-org/pyterrier#352]
**Describe the bug**
I have created an index with very specific tweet texts and then a simple pipeline along the lines of  
`
pipeline = (tuned_bm25 >> 
            pt.text.get_text(index_ref, ["retweet_score"]) >> 
            pt.apply.doc_score(pipeline_scorer))` 
to perform reranking. I then searched using `pipeline.search()` for words which I know doesn't exist in the index ( in my case it was `macaw` and `thesaurus`). It leads to the following error 
```
  File "/mnt/c/Users/prith/Desktop/SI650/ice/si_650_final_project/search.py", line 93, in search
    search_result = (pipeline % int(count)).search(term)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/transformer.py", line 168, in search
    rtr = self.transform(queryDf)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/ops.py", line 189, in transform
    res = self.transformer.transform(topics_and_res)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/ops.py", line 331, in transform
    topics = m.transform(topics)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/ops.py", line 331, in transform
    topics = m.transform(topics)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/apply_base.py", line 199, in transform
    return fn(inputRes)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/text.py", line 97, in add_text_generic
    return add_text_function_docids(res)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/text.py", line 90, in add_text_function_docids
    res[k] = allmeta[i]
IndexError: index 0 is out of bounds for axis 0 with size 0
``` 

**To Reproduce**
1. Any index which does not span all of known vocabulary
2. `
pipeline = (tuned_bm25 >> 
            pt.text.get_text(index_ref, ["retweet_score"]) >> 
            pt.apply.doc_score(pipeline_scorer))` 
3. Use `search` for a specific term which doesn't exist in the index vocabulary

**Expected behavior**
There should be no-error with an empty dataframe as output

**Documentation and Issues**
 - [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
 - [ ] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Comment by cmacdonald** [comment]
Good spot. We’ve seen a few of these empty DF bugs. It should be easy to tidy this up for the next point release

**Comment by cmacdonald** [comment]
So your error is from pt.text.get_text(); But pt.apply.doc_score() could also have given an error. I've patched both in #353.

Could you test with that branch?

**Comment by prithvidasgupta** [comment]
Yes this works! Thank you for the quick turnaround @cmacdonald ! 

Although pushing the pipeline to an `IdentityTransformer` for L2R features leads to a `ValueError: Got no results from IdentityTransformer(), expected 0` but I believe that is by design. Is there any particular reason for this choice?

**Comment by cmacdonald** [comment]
https://github.com/terrier-org/pyterrier/blob/master/pyterrier/ops.py#L227

Yes, that check might be too aggressive...

**Comment by cmacdonald** [comment]
More fixes on the same branch. Over to you.

**Comment by prithvidasgupta** [comment]
My usecase is to make a searchable index with scientific names for all birds posted on #IndiAves over on Twitter. Now this hashtag  is usually used by Indian birders and hence only has Indian birds. A `macaw` is not an Indian bird and hence is missing from the entire index. I believe anyone making a search engine for hyper-focused domains such as mine would face these issues. 

But again that might just be me 😃.

**Comment by prithvidasgupta** [comment]
After the fixes, it's a different error as stated below (a Terrier exception). However now that I think about it the `IdentityTransformer` ValueError is justified ( I thought why would you add features to a frame that is already empty? It should definitely error out. )

```
Traceback (most recent call last):
  File "/mnt/c/Users/prith/Desktop/SI650/ice/si_650_final_project/search.py", line 97, in search
    search_result = (pipeline % int(count)).search(term)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/transformer.py", line 168, in search
    rtr = self.transform(queryDf)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/ops.py", line 190, in transform
    res = self.transformer.transform(topics_and_res)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/ops.py", line 335, in transform
    topics = m.transform(topics)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/ops.py", line 335, in transform
    topics = m.transform(topics)
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/ops.py", line 227, in transform
    results = m.transform(inputRes.copy())
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/batchretrieve.py", line 495, in transform
    indexref = DFIndexer(None, type=IndexingType.MEMORY, verbose=self.verbose).index(documents[self.body_attr], documents["docno"])
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/index.py", line 666, in index
    index = self.createIndexer()
  File "/home/prithvid/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pyterrier/index.py", line 478, in createIndexer
    index = Indexer()
  File "jnius/jnius_export_class.pxi", line 271, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 385, in jnius.JavaClass.call_constructor
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: For input string: "nan" java.lang.NumberFormatException
```
My current pipeline looks like 

```
def pipeline_scorer(row):
    return float(Math.ceil((row['features'][1]*row['features'][0])/5))+Math.log10(float(row['retweet_score'])+1.0)
   
pipeline = (tuned_bm25 >> 
            pt.text.get_text(index_ref, ["retweet_score", "classifier_text"]) >>  
           ( pt.transformer.IdentityTransformer() ** 
            pt.text.scorer(body_attr='classifier_text', wmodel = bm25_tuning_helper(1.2,8,0.25), background_index = index)
            ) >>
            pt.apply.doc_score(pipeline_scorer))
```

**Comment by cmacdonald** [comment]
> However now that I think about it the IdentityTransformer ValueError is justified ( I thought why would you add features to a frame that is already empty? It should definitely error out. )

I think all pipelines should execute fine with empty input df. 

Nice pipeline! `bm25_tuning_helper` will be slow for large numbers of docs but perhaps worth trying for small corpora - the cost of crossing the JNI boundary for every posting scored is non trivial. 

There is a trick to print the Java stacktrace, which will help me debug your problem:
```python
from jnius import JavaException
try:
  search_result = (pipeline % int(count)).search(term)
except JavaException as ja:
  print(ja.stacktrace)
  raise ja
```

**Comment by cmacdonald** [comment]
> I think all pipelines should execute fine with empty input df.

So having asserted that I have to back myself up. Branch updated (https://github.com/terrier-org/pyterrier/commit/572371d883771a30069d0b4bf5c032ff487920f0), should fix this problem with `pt.text.scorer` on empty dfs. 

Thanks for your patience @prithvidasgupta on these edge cases that we dont systematically test.

**Comment by cmacdonald** [comment]
All good now @prithvidasgupta ?

**Comment by prithvidasgupta** [comment]
Hey @cmacdonald I have a couple of exams for this week and haven't got the time to test this out. Is it alright if I confirm it over the weekend?

**Comment by cmacdonald** [comment]
No problem! Best of luck!

**Comment by prithvidasgupta** [comment]
@cmacdonald just now tested with my pipeline. everything looks good now! thanks for all your help!

**Comment by cmacdonald** [comment]
Ace, thanks for testing. Feel free to let us know future any future questions or problems!
