### ISSUE TITLE
JVM exception occurred: org/terrier/python/MemoryIndexer java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Watheq9** [terrier-org/pyterrier#355]
Hi @cmacdonald  and @seanmacavaney, 

While I was trying to create an index using IterDictIndexer, I received NoClassDefFoundError error.

This is the snippet I used with Python 3.6 and python-terrier 0.7.1. 

`index_save_path = 'path/to/save/my/index'
iter_indexer = pt.IterDictIndexer(index_save_path,  overwrite=True, verbose=True)`

And this is the error message:

```
JVM exception occurred: org/terrier/python/MemoryIndexer java.lang.NoClassDefFoundError
Traceback (most recent call last):
  File "/ds/usr/watheq/fakedet/IndexUtility.py", line 63, in build_multi_field_index
    iter_indexer = pt.IterDictIndexer(index_save_path,  overwrite=True, verbose=True)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/pyterrier/index.py", line 578, in __init__
    Indexer.__init__(self, index_path, *args, **kwargs)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/pyterrier/index.py", line 261, in __init__
    run_autoclass()
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/pyterrier/index.py", line 84, in run_autoclass
    BasicMemoryIndexer = autoclass("org.terrier.python.MemoryIndexer")
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/jnius/reflect.py", line 229, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: org/terrier/python/MemoryIndexer java.lang.NoClassDefFoundError
```

However, when I tried the same snippet on a different environment with python 3.7.9 and python-terrier==0.9.1, I didn't get any error. 

For the environment I am working on, I cannot change the python version which is 3.6 as other modules in the project depend on this version. I tried to upgrade python terrier to 0.9.1, but didn't work as Python 3.6 only supports upgrading python-terrier up to 0.7.2 only. 

I appreciate your help in fixing this issue.

Regards,
Watheq

**Comment by cmacdonald** [comment]
Hi @Watheq9.

The error is caused by  a mismatch in a jar file called terrier-python-helper version - PyTerrier downloads the newest version, and that version doesnt work for older PyTerrier in this particular edge case.

I can probably fix this by making a new terrier-python-helper release. 
If your older version of PyTerrier supports it `pt.init(helper_version = "0.0.6")` should address your problem as a workaround.

I would recommend upgrading Python (and PyTerrier versions if you can). Python 3.6 is End-of-life.

**Comment by Watheq9** [comment]
Hi @cmacdonald,

Thanks for your reply!

I tried what you suggested but the received the following error:
```

init() got an unexpected keyword argument 'helper_version'
Traceback (most recent call last):
  File "/ds/usr/watheq/fakedet/IndexUtility.py", line 17, in __init__
    pt.init(boot_packages=["com.github.terrierteam:terrier-prf:-SNAPSHOT"], helper_version = "0.0.6")
TypeError: init() got an unexpected keyword argument 'helper_version'
```

After that, I checked the argument names and found an argument named 'version'. So, I used that argument with these values [0.0.6,  0.6.0, 0.7.1], but all of them resulted in the same following error:

```
terrier-assemblies 0.0.6  jar-with-dependencies not found, downloading to /ds/usr/watheq/.pyterrier...
Could not fetch https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/0.0.6/terrier-assemblies-0.0.6-jar-with-dependencies.jar
Traceback (most recent call last):
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/pyterrier/mavenresolver.py", line 45, in downloadfile
    wget.download(mvnUrl, file_path)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ds/usr/watheq/fakedet/IndexUtility.py", line 17, in __init__
    pt.init(version = "0.0.6")
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/pyterrier/__init__.py", line 90, in init
    classpathTrJars = setup_terrier(HOME_DIR, version, boot_packages=boot_packages)
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/pyterrier/bootstrap.py", line 97, in setup_terrier
    trJar = mavenresolver.downloadfile(TERRIER_PKG, "terrier-assemblies", terrier_version, file_path, "jar-with-dependencies")
  File "/ds/usr/shared/conda/fakedet_shared/lib/python3.6/site-packages/pyterrier/mavenresolver.py", line 47, in downloadfile
    raise ValueError("Could not fetch " + mvnUrl) from he
ValueError: Could not fetch https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/0.0.6/terrier-assemblies-0.0.6-jar-with-dependencies.jar
```

**Comment by cmacdonald** [comment]
no, version is different. 

I'm looking at the source of __init.py for v0.7.1 (which you say you have):
https://github.com/terrier-org/pyterrier/blob/e6ba40c65e64bf8bf21591e84f124be8e92eaae0/pyterrier/__init__.py#L35
and I can see the helper_version kwarg?

Anyway, you can amend your source code to force the helper version at
https://github.com/terrier-org/pyterrier/blob/e6ba40c65e64bf8bf21591e84f124be8e92eaae0/pyterrier/__init__.py#L94

**Comment by Watheq9** [comment]
This worked successfully 👍.
You're right; no need for an amendment for 0.7.1, but I amended it for 0.6.0.

Thanks a lot @cmacdonald!

**Comment by cmacdonald** [comment]
Ace :-)

**Comment by Watheq9** [comment]
@cmacdonald, I have a question. How can I know the helper version that suits a specific pyterrier version?

**Comment by cmacdonald** [comment]
I think that we are keen to keep people moving through PyTerrier version, as we do fix bugs, and its difficult to support a plethora of older versions for research software. I think Pyserini have locked to particular Anserini versions - we were keen not to lock, as it allowed Java fixes to help older version as well, without needing to do a PyTerrier release.

Terrier-core and helpers are only released as and when needed (e.g. new functionality for PyTerrier), but tend to be aligned in timing to particular PyTerrier versions: 
You can see the helper version release dates here:
https://central.sonatype.dev/artifact/org.terrier/terrier-python-helper/0.0.7/versions
and similarly 
https://central.sonatype.dev/artifact/org.terrier/terrier-platform/5.7/versions for Terrier.
PyTerrier release history is at https://pypi.org/project/python-terrier/#history
