### ISSUE TITLE
Retrieval breaks for a query with punctuation marks

### ISSUE THREAD

**Issue by mihirs16** [terrier-org/pyterrier#376]
**Describe the bug**

When using `BatchRetrieve` if there are any punctuation marks (e.g. "?", "'"), the `BatchRetrieve.search` breaks. However, if I input a clean query (i.e. a query without punctuation marks) it works as expected.

**To Reproduce**

1. Custom Index (using [CODEC](https://github.com/grill-lab/CODEC))

```python
import pyterrier as pt; pt.init()
from pyterrier.index import IterDictIndexer

# from codec_se import iter_file

def iter_file(filename):
    """
    load jsonl as a generator
    """
    with open(filename, 'rt') as file:
        for each_row in file:
            each_row_data = json.loads(each_row)
            each_row_data['docno'] = each_row_data.pop('id')
            each_row_data['text'] = each_row_data.pop('contents')
            yield each_row_data

indexer = IterDictIndexer(
    index_path='./index',
    meta={'docno': 32},
    overwrite=True
)
indexref = indexer.index(iter_file('data/doc_corpus/sample_codec_documents.jsonl'))
```

2. "BM25" using `BatchRetrieve`

```python
index = pt.IndexRef.of("./index/data.properties")
bm25 = BatchRetrieve(index, wmodel="BM25")
```

3. Experiment using `BatchRetrieve` and dataframes of topics and qrels.

```python
# single query search from stored index
results = bm25.search("How has the UK Open Banking Regulation benefited challenger banks?")
print(results.head())

# run experiments and eval
experiment = pt.Experiment(
    [bm25],
    codec_se.get_topics(),
    codec_se.get_qrels(),
    eval_metrics=["ndcg"]
)
print(experiment.head())
```

4. What was the dataframe output

```
# codec_se.get_topics()
           qid                                              query
0  economics-1  How has the UK Open Banking Regulation benefit...
1  economics-2  What technological challenges does Bitcoin fac...
2  economics-3  Why are many commentators arguing NFTs are the...
3  economics-4  Why has value investing underperformed growth ...
4  economics-6  Why are some economists sceptical about the EU...


# codec_se.get_qrels()
           qid ignore                             docno  label
0  economics-8     Q0  089a22846f6ba15fb4ef4cca0a884dd4      1
1  economics-8     Q0  0b2b173ef8348037ad80067ff37f0955      0
2  economics-8     Q0  0f78f8ec15ffec5ee7b8428af6b78683      0
3  economics-8     Q0  106e0f2b21616c3b30fd3b82127e4f5e      0
4  economics-8     Q0  143dc397c844340d13db74d4a34a78b8      0


# <NO OUTPUT IF QUERY CONTAINS PUNCTUATION MARKS>


# single search output for a clean query
  qid  docid                             docno  rank      score                                              query
0   1   1039  849c1144a41654459fd1447d9600fc7b     0  26.647895  How has the UK Open Banking Regulation benefit...
1   1   2176  169ed16f982c6fdaf26a237a86aec5da     1  23.666817  How has the UK Open Banking Regulation benefit...
2   1   2859  f54ca3e79084a61593f97e904c9d01f8     2  23.104976  How has the UK Open Banking Regulation benefit...
3   1   1456  e46a1256b63f42bbd3ddade7d289fc89     3  22.498401  How has the UK Open Banking Regulation benefit...
4   1   1174  657bb2db8bf32754de2133530542a459     4  22.425985  How has the UK Open Banking Regulation benefit...
```

5. Following are the errors for a single search and experiment (for a queries with punctuation marks) respectively

```
Traceback (most recent call last):
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/experiments/retrieval_se.py", line 13, in <module>
    results = bm25.search("How has the UK Open Banking Regulation benefited challenger banks?")
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/venv/lib/python3.10/site-packages/pyterrier/transformer.py", line 168, in search
    rtr = self.transform(queryDf)
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/venv/lib/python3.10/site-packages/pyterrier/batchretrieve.py", line 441, in transform
    res = self._retrieve_one(row, input_results, docno_provided=docno_provided, docid_provided=docid_provided, scores_provided=scores_provided)
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/venv/lib/python3.10/site-packages/pyterrier/batchretrieve.py", line 352, in _retrieve_one
    self.manager.runSearchRequest(srq)
  File "jnius/jnius_export_class.pxi", line 885, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 982, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Failed to process qid 1 'How has the UK Open Banking Regulation benefited challenger banks?' -- Lexical error at line 1, column 67.  Encountered: <EOF> after : "" org.terrier.querying.parser.QueryParserException
```

```
Traceback (most recent call last):
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/experiments/retrieval_se.py", line 17, in <module>
    experiment = pt.Experiment(
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/venv/lib/python3.10/site-packages/pyterrier/pipelines.py", line 450, in Experiment
    time, evalMeasuresDict = _run_and_evaluate(
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/venv/lib/python3.10/site-packages/pyterrier/pipelines.py", line 170, in _run_and_evaluate
    res = system.transform(topics)
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/venv/lib/python3.10/site-packages/pyterrier/batchretrieve.py", line 441, in transform
    res = self._retrieve_one(row, input_results, docno_provided=docno_provided, docid_provided=docid_provided, scores_provided=scores_provided)
  File "/Users/mihirsingh/Documents/GitHub/info-retrieval/multi-stage-retrieval-using-splade-and-t5/venv/lib/python3.10/site-packages/pyterrier/batchretrieve.py", line 352, in _retrieve_one
    self.manager.runSearchRequest(srq)
  File "jnius/jnius_export_class.pxi", line 885, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 982, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Failed to process qid economics-1 'How has the UK Open Banking Regulation benefited challenger banks?' -- Lexical error at line 1, column 67.  Encountered: <EOF> after : "" org.terrier.querying.parser.QueryParserException
```

**Expected behavior**
Expected behavious was that PyTerrier would handle the punctuation marks and remove any punctuation at indexing and while using a query as input, atleast for the experiment (if I understand correctly).

**Documentation and Issues**

- [x] I have checked the [PyTerrier documentation](https://pyterrier.readthedocs.io/en/latest/) for relevant content
- [x] I have checked for previous relevant [PyTerrier issues](https://github.com/terrier-org/pyterrier/issues)

**Comment by cmacdonald** [comment]
The Terrier has a query language. We want to support that query language. 
However, what we do is for most datasets, we remove the puncutation etc on ingestion of the topic.

If your case, you can put `pt.rewrote.tokenise()` in front of BM25

https://pyterrier.readthedocs.io/en/latest/rewrite.html#tokensing-the-query
