### ISSUE TITLE
pytz: No module named 'zoneinfo'

### ISSUE THREAD

**Issue by tsgiannis** [terrier-org/pyterrier#388]
Trying to use pyterrier bombs out right away with message
pytz: No module named 'zoneinfo'
![image](https://user-images.githubusercontent.com/14885251/232778835-19dbbc58-2153-4164-8a4e-7dc6c76d47e2.png)

Running on clean vanilla Ubuntu Desktop latest version
Installed Python 3.8 for maximum compatibility (clean)
![image](https://user-images.githubusercontent.com/14885251/232779546-71192cea-c727-4315-b1bb-11ccf1ecb884.png)

I guess this is the bare minimum to start using Pyterrier
![image](https://user-images.githubusercontent.com/14885251/232779968-1f496812-c6ab-4be2-97bd-f9d1b24e2262.png)
Any ideas ?

**Comment by cmacdonald** [comment]
can you show the full stack trace for the first picture? 

Why do you set `os.environ['TZ']` in your opening? Are you sure thats needed?

**Comment by tsgiannis** [comment]
> can you show the full stack trace for the first picture?
> 
> Why do you set `os.environ['TZ']` in your opening? Are you sure thats needed?

Thanks for replying
The os.environ['TZ'] = 'UTC' was suggested by ChatGPT after trying everything that simply wouldn't work


```
/usr/bin/python3.8 /home/master/PycharmProjects/terrier/indexing.py 
Traceback (most recent call last):
  File "/home/master/PycharmProjects/terrier/indexing.py", line 2, in <module>
    import pyterrier as pt
  File "/home/master/.local/lib/python3.8/site-packages/pyterrier/__init__.py", line 8, in <module>
    from .transformer import Transformer, Estimator, Indexer
  File "/home/master/.local/lib/python3.8/site-packages/pyterrier/transformer.py", line 4, in <module>
    import pandas as pd
  File "/home/master/.local/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
pytz: No module named 'zoneinfo'
```

**Comment by cmacdonald** [comment]
Have you tried removing it?

It seems to be an error raised by Pandas. Do you know what pandas version you have installed? 

I suspect `import pandas as pd` would have the same error. I dont know enough about what is going on to help.

Perhaps try using anconda installation of Python rather than Debian's.

Works fine on Colab
https://colab.research.google.com/drive/1FLS84Vfv_3SFFJS_PLocUSXdMk5sKact?usp=sharing

**Comment by tsgiannis** [comment]
Update you can close this bug with a small note
I updated pytz to the latest version and the error went away
The default package was 2021.xx and updating to the last available allowed pyterrier to start
now other issues emerged  but I will try to resolve them.

**Comment by cmacdonald** [comment]
Good stuff, thx. Let us know if you need further assistance.
